// <auto-generated />
namespace commenergy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class commenergylayerarticlecs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commenergylayerarticlecs));
        
        string IMigrationMetadata.Id
        {
            get { return "201312050605273_commenergy.layer.article.cs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
