// <auto-generated />
namespace commenergy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class commenergyModelscommenergyContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commenergyModelscommenergyContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201312021619264_commenergy.Models.commenergyContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
