// <auto-generated />
namespace commenergy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class sccc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sccc));
        
        string IMigrationMetadata.Id
        {
            get { return "201405030056071_sccc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
