// <auto-generated />
namespace commenergy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _abstract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_abstract));
        
        string IMigrationMetadata.Id
        {
            get { return "201403071155295_abstract"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
