// <auto-generated />
namespace commenergy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class M9887 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M9887));
        
        string IMigrationMetadata.Id
        {
            get { return "201409172131490_M9887"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
