// <auto-generated />
namespace commenergy.Models.appContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class d : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d));
        
        string IMigrationMetadata.Id
        {
            get { return "201403150352003_d"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
