// <auto-generated />
namespace commenergy.Models.appContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class e : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(e));
        
        string IMigrationMetadata.Id
        {
            get { return "201403261108206_e"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
